window.seraph_accel||(window.seraph_accel={});
(function(){seraph_accel.PluginAdmin={AdvertProductsContentInit:function(a,c,b,e,h,g){function l(k,q){var f="";if(Array.isArray(k)&&k.length){f+=seraph_accel.Ui.TagOpen("tr");for(var d=0;d<k.length;d++){var m=k[d];0<d&&0==d%h&&(f+=seraph_accel.Ui.TagClose("tr")+seraph_accel.Ui.TagOpen("tr"));var x=seraph_accel.Ui,C=x.Tag,y=seraph_accel.Ui,D=y.Tag,z=q,r="";var p=m.images;var u=z;if(Array.isArray(p)){for(var v=-1,A=2147483647,w=-1,B=2147483647,t=0;t<p.length;t++){var n=p[t];if(u==n.width){v=t;break}u<
n.width?(n=n.width-u,n<A&&(v=t,A=n)):(n=u-n.width,n<B&&(w=t,B=n))}p=-1!=v?p[v].url:-1!=w?p[w].url:null}else p=null;p&&(r+=seraph_accel.Ui.Tag("td",seraph_accel.Ui.Link(seraph_accel.Ui.Tag("img",null,{"class":"ctlSpaceAfter",width:z,src:p},!0),m.urlInfo,!0),{style:{width:"1px"}}));r+=seraph_accel.Ui.TagOpen("td");r+=seraph_accel.Ui.Tag("h3",m.title,{"class":"ctlSpaceVAfter",style:{"margin-top":0}});r+=seraph_accel.Ui.Tag("div",m.descr);m.urlInfo&&(r+=seraph_accel.Ui.Button(e,!0,null,"ctlSpaceVBefore",
"button",{onclick:"window.open( '"+m.urlInfo+"', '_blank' )"}));r+=seraph_accel.Ui.TagClose("td");m=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",seraph_accel.Ui.Tag("row",r)));f+=C.call(x,"td",D.call(y,"div",m,{style:{margin:"1em 1em 2em 1em"}}),{"class":"cx-lg-6 cx-xs-12",style:{"vertical-align":"top"}})}for(;d%h;d++)f+=seraph_accel.Ui.Tag("td",null,{"class":"cx-lg-6 cx-xs-12"});f+=seraph_accel.Ui.TagClose("tr");f=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",f))}jQuery(a).html(f)}
jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(c+"/v1/advert_products",{slug:"accelerator",locale:b}),type:"GET",dataType:"json"}).then(function(k){l(k,g)},function(k){l(null,0)})},SwitchTo:function(a,c,b,e,h,g,l){function k(d,m){d?q.find(".operateblock").hide():q.find(".operateblock").find("*").prop("disabled",!1);f.removeClass("notice-warning updating-message");f.addClass(d?"notice-success updated-message":"notice-error");f.find("p").text(m);d&&q.find(".refresh_after").prop("checked")&&setTimeout(function(){location.reload()},
0)}var q=jQuery(".seraph_accel_switchto"),f=q.find(".update-message");f.removeClass("notice-success notice-error updated-message");f.addClass("notice-warning updating-message");f.find("p").text(c);q.find(".operateblock").find("*").prop("disabled",!0);f.show();jQuery.ajax({url:e,type:"post"}).then(function(d){return jQuery.ajax({url:h,type:"post",data:{action:"update-plugin",plugin:g,slug:"seraphinite-accelerator",_ajax_nonce:l,seraph_accel_switchto:a},dataType:"json"})}).then(function(d){d.success?
k(!0,b):k(!1,d.data.errorMessage)},function(d){k(!1,"OK"===d.statusText?"PHP error: "+d.responseText:"Backend error: "+d.status+" "+d.statusText)})},RateItCont_Set:function(a,c,b){var e=jQuery("#"+a),h=e.find(".actions"),g=e.find(".seraph_accel_spinner");h.hide();g.show();jQuery.ajax({url:b+"="+(c?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(l){e.hide()},function(l){h.show();g.hide()})},RateIt_Set:function(a,c){jQuery("#seraph_accel_RateIt_Message .actions").hide();jQuery("#seraph_accel_RateIt_Message .seraph_accel_spinner").show();
jQuery.ajax({url:c+"="+(a?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(b){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_RateIt_Message"))},function(b){jQuery("#seraph_accel_RateIt_Message .actions").show();jQuery("#seraph_accel_RateIt_Message .spinner").hide()})},ChangeVersion_Confirm:function(a){jQuery("#seraph_accel_ChangeVersion_Msg .actions").hide();jQuery("#seraph_accel_ChangeVersion_Msg .seraph_accel_spinner").show();jQuery.ajax({url:a+"=changeVersionConfirm",type:"post"}).then(function(c){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_ChangeVersion_Msg"))},
function(c){jQuery("#seraph_accel_ChangeVersion_Msg .actions").show();jQuery("#seraph_accel_ChangeVersion_Msg .spinner").hide()})},SettImport:function(a,c,b){function e(){g.prop("disabled",!1);h.hide()}if(b){a=jQuery(a.parentNode);var h=a.find(".seraph_accel_spinner"),g=a.find("input.button");g.prop("disabled",!0);h.show();a=new FileReader;a.onabort=function(l){e()};a.onerror=function(l){e()};a.onload=function(l){jQuery.ajax({url:c+"=settImport",type:"post",contentType:"application/json",data:l.target.result}).then(function(){location.reload()},
function(k){e()})};a.readAsText(b)}},SettExport:function(a,c){function b(g){g&&window.saveAs(new Blob([g],{type:"text/json"}),"seraphinite-accelerator-settings.json");h.prop("disabled",!1);e.hide()}a=jQuery(a.parentNode);var e=a.find(".seraph_accel_spinner"),h=a.find("input.button");h.prop("disabled",!0);e.show();jQuery.ajax({url:c+"=settExport",type:"post"}).then(function(g){seraph_accel.Ui.ScriptLoad(document,"https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js","file-saver").then(function(){b(g)},
function(l){b()})},function(g){b()})},OnSettWizNext:function(a,c){var b=jQuery(a).closest("form");a=jQuery(a.parentNode);var e=b.find(".wizPages");b=e.find(">.active").first();b.get(0)?(c=c?b.next():b.prev(),c.get(0)&&(b.removeClass("active"),b=c)):b=e.children().first();b.addClass("active");c=!!b.next().get(0);b=!!b.prev().get(0);a.find("input.wizNext").prop("disabled",!c);a.find("input.wizPrev").prop("disabled",!b);c?a.find("input.wizFinish").hide():a.find("input.wizFinish").show()}}})();
